import type { z } from "zod";
import type * as s from "../api/schemas/task";
export type TaskStatus = z.infer<typeof s.TaskStatusSchema>;
export type PolicyDecision = "ALLOW" | "DENY";
export type AssetView = z.infer<typeof s.AssetViewSchema>;
export type MandateView = z.infer<typeof s.MandateViewSchema>;
export type CreateTaskRequest = z.infer<typeof s.CreateTaskRequestSchema>;
export type TaskView = z.infer<typeof s.TaskViewSchema>;
export type QuoteView = z.infer<typeof s.QuoteViewSchema>;
export type QuoteList = z.infer<typeof s.QuoteListSchema>;
export type PolicyReasonCode = z.infer<typeof s.PolicyReasonCodeSchema>;
export type PolicyView = z.infer<typeof s.PolicyViewSchema>;
export type PaymentView = z.infer<typeof s.PaymentViewSchema>;
export type AttemptCreateRequest = z.infer<typeof s.AttemptCreateRequestSchema>;
export type AttemptView = z.infer<typeof s.AttemptViewSchema>;
export type AiProposalResponse = z.infer<typeof s.AiProposalResponseSchema>;
export type EventView = z.infer<typeof s.EventViewSchema>;
export type EventPage = z.infer<typeof s.EventPageSchema>;
export type TaskAsset = AssetView;
export type Mandate = MandateView;
export type TaskAttempt = AttemptView;
export type TaskQuote = QuoteView;
export type TaskQuotesResponse = QuoteList;
export type TaskEventsResponse = EventPage;
export type CreateAttemptRequest = AttemptCreateRequest;
export type AIProposalResponse = AiProposalResponse;
export type StopTaskAction = "mandate/reject" | "cancel";
